dist: xenial
language: node_js
node_js: "12"
sudo: required

matrix:
  fast_finish: true
  include:
    # WASM Build
    - env: TEST=WASM PSP_DOCKER=1
      services: docker

    # Python 3.7 Linux build
    - python: "3.7"
      language: python
      env: TEST=PYTHON PSP_DOCKER=1
      cache: pip
      services: docker

    # Python 3.7 Linux manylinux2010 build
    - python: "3.7"
      language: python
      env: TEST=PYTHON_MANYLINUX2010 PSP_DOCKER=1
      cache: pip
      services: docker

    # Python 3.7 Linux manylinux2014 build
    - python: "3.7"
      language: python
      env: TEST=PYTHON_MANYLINUX2014 PSP_DOCKER=1
      cache: pip
      services: docker

    # Python 3.7 Mac build
    - env: TEST=PYTHON
      cache: pip
      os: osx
      osx_image: xcode11.2

    # Python 2.7 Linux build
    - python: "2.7"
      language: python
      env: TEST=PYTHON2 PSP_DOCKER=1
      cache: pip
      services: docker

    # Python 2.7 Linux manylinux2010 build
    - python: "2.7"
      language: python
      env: TEST=PYTHON2_MANYLINUX2010 PSP_DOCKER=1
      cache: pip
      services: docker

    # Python 2.7 Mac build
    - env: TEST=PYTHON2
      cache: pip
      os: osx
      osx_image: xcode11.2

  allow_failures:
    # Mac builds get extensively tested by the core developers.
    # They are also extremely slow to load on travis.
    # So pull requests should check these, but they are allowed
    # to fail

    # Python 3.7 Linux manylinux2014 build
    - python: "3.7"
      language: python
      env: TEST=PYTHON_MANYLINUX2014 PSP_DOCKER=1
      cache: pip
      services: docker

    # Python 3.7 Mac build
    - env: TEST=PYTHON
      cache: pip
      os: osx
      osx_image: xcode11.2

    # Python 2.7 Mac build
    - env: TEST=PYTHON2
      cache: pip
      os: osx
      osx_image: xcode11.2


env:
  global:
    - EM_USE_GLOBAL_CACHE=1

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-all-dev
      - libtbb-dev
      - gcc-4.9
      - g++-4.9
  homebrew:
    update: true
    packages:
      - python
      - python2
      - pybind11
      - cmake
      - boost
      - tbb
      - flatbuffers
      - rapidjson


before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then npm install -g yarn; fi

install:
  - node --version
  - yarn

script:
  - touch .perspectiverc
  - if [ "$TEST" = "WASM" ]; then yarn lint; fi
  - if [ "$TEST" = "WASM" ]; then yarn build_js; fi
  - if [ "$TEST" = "WASM" ]; then yarn test_js --quiet; fi
  - if [ "$TEST" = "PYTHON" ]; then yarn build_python --ci; fi
  - if [ "$TEST" = "PYTHON2" ]; then yarn build_python --ci --python2; fi
  - if [ "$TEST" = "PYTHON_MANYLINUX2010" ]; then yarn build_python --ci --manylinux2010; fi
  - if [ "$TEST" = "PYTHON_MANYLINUX2014" ]; then yarn build_python --ci --manylinux2014; fi
  - if [ "$TEST" = "PYTHON2_MANYLINUX2010" ]; then yarn build_python --ci --manylinux2010 --python2; fi
